apiVersion: v2
name: folonite-agent
description: A Helm chart for Folonite Agent service
type: application
version: 0.1.0
appVersion: "edge"
dependencies:
  - name: postgresql
    version: "~13.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
keywords:
  - folonite
  - agent
  - api
maintainers:
  - name: Folonite Team
sources:
  - https://github.com/folonite-ai/folonite